//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace MySite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="Поле Login обязательное для исполнения")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Поле Password обязательное для исполнения")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Поле Email обязательное для исполнения")]
        [RegularExpression(@".+\@.+\..+", ErrorMessage = "Неверный формат Email (ХХХ@mail.ru)")]
        public string Email { get; set; }
    }
}
